export const meatedata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            Dashboard lkjg
            <body>{children}</body>
        </html>
    )
}